language: node_js
node_js:
  - 0.6
  - 0.8
  - 0.10
  - 0.11
script: 
  - "node samples/Usage-Options.js"
  - "node samples/Usage-Simple.js"
  - "node samples/Usage-Buffer.js"
  - "node src/JSss.js"
  - "node src/S3Api.js"
notifications:
  email: dev@totendev.com
  irc:
    channels:
      - "irc.freenode.org#TotenDev"
